Watch/Areas/Admin/Controllers/CoverTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Watch.DataAccess;
using Watch.DataAccess.Repository.IRepository;
using Watch.Models;

namespace Watch.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitofWork _unitOfWork;

        public CoverTypeController(IUnitofWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> objcategoryList = _unitOfWork.CoverType.GetAll();
            return View(objcategoryList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType Created Successfully";
                return RedirectToAction("Index");
            }
                return View(obj);
        }

        //GET
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.WatchCategories.Find(id);
            //var categoryFromDb = _db.GetFirstorDefault(u => u.Id == id);
            var categoryFromDb = _unitOfWork.CoverType.GetFirstorDefault(u => u.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
              // _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "CoverType Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
         //GET
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //var categoryFromDb = _db.WatchCategories.Find(id);
            //var categoryFromDb = _db.GetFirstorDefault(u => u.Id ==id);
            var categoryFromDb = _unitOfWork.CoverType.GetFirstorDefault(u => u.Id == id);
            if (categoryFromDb == null)
            {
                return NotFound();
            }
            return View(categoryFromDb);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _unitOfWork.CoverType.GetFirstorDefault(u => u.Id == id);
            if (id == null || id == 0)
            {
                return NotFound();
            }

            _unitOfWork.CoverType.Remove(obj);
            _unitOfWork.Save();
            TempData["success"] = "CoverType Deleted Successfully";
            return RedirectToAction("Index");
            }

    }
}

Watch/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-5" >
        <div class="row pb-3">
            <h3 class="text-primary p-2">Create CoverType</h3>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
            <br/>
            
        </div>
        <div>
            <button type="submit" class="btn btn-warning" style="width:150px" >Create </button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Watch/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id"  hidden/>
    <div class="border p-3 mt-5" >
        <div class="row pb-3">
            <h3 class="text-primary p-2">Delete CoverType</h3>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
            <br/>
            </div>
        <div>
            <button type="submit" class="btn btn-warning" style="width:150px" >Delete </button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Cancle</a>
        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Watch/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-5" >
        <div class="row pb-3">
            <h3 class="text-primary p-2">Edit CoverType</h3>
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
            <br/>
            
        </div>
        <div>
            <button type="submit" class="btn btn-warning" style="width:150px" >Update </button>
            <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back To List</a>
        </div>
    </div>

</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Watch/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
   <div class="row pt-4">

    <div class="col-6" >

        <h1 class="text-primary">CoverType List</h1>
    </div>
    <div class="col-6 text-end" >
           
        <a class=" btn btn-primary" asp-Controller="CoverType" asp-action="Create">
                <i class="bi bi-plus-circle"></i> Create new CoverType
        </a>
    </div>
    </div>
    <br/>

<table class="table table-bordered table-striped text-primary" style="width:100%">
    <thead>
        <tr>
            <th>
                    CoverType Name
            </th> 
            
            <th>

            </th>
        </tr>
    </thead>
        <tbody class="text-black">
        @foreach(var obj in Model)
        {
            <tr >
                <td width="40%">
                    @obj.Name
                </td>
                
                <td class=" btn-group" role="group">
                        <a class="btn btn-primary mx-1" asp-asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id"><i class="bi bi-pencil-square"></i> Edit</a>
                        <a class="btn btn-danger  mx-1" asp-asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id"><i class="bi bi-trash3"></i> Delete</a>
                </td>
            </tr>
        }
    </tbody>

</table>
</div>